USE [vizsga]
GO
CREATE APPLICATION ROLE [AppRole] WITH DEFAULT_SCHEMA = [Customer], PASSWORD = N'AppRole2021'
GO
GRANT ALTER ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT CONTROL ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT CREATE SEQUENCE ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT DELETE ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT EXECUTE ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT INSERT ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT REFERENCES ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT SELECT ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT UPDATE ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT VIEW CHANGE TRACKING ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT VIEW DEFINITION ON SCHEMA::[Customer] TO [AppRole]
GO
DENY TAKE OWNERSHIP ON SCHEMA::[Customer] TO [AppRole]
GO
GRANT ALTER ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT CONTROL ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT CREATE SEQUENCE ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT DELETE ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT EXECUTE ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT INSERT ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT REFERENCES ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT SELECT ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT UPDATE ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT VIEW CHANGE TRACKING ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT VIEW DEFINITION ON SCHEMA::[Orders] TO [AppRole]
GO
DENY TAKE OWNERSHIP ON SCHEMA::[Orders] TO [AppRole]
GO
GRANT ALTER ON SCHEMA::[Product] TO [AppRole]
GO
GRANT CONTROL ON SCHEMA::[Product] TO [AppRole]
GO
GRANT CREATE SEQUENCE ON SCHEMA::[Product] TO [AppRole]
GO
GRANT DELETE ON SCHEMA::[Product] TO [AppRole]
GO
GRANT EXECUTE ON SCHEMA::[Product] TO [AppRole]
GO
GRANT INSERT ON SCHEMA::[Product] TO [AppRole]
GO
GRANT REFERENCES ON SCHEMA::[Product] TO [AppRole]
GO
GRANT SELECT ON SCHEMA::[Product] TO [AppRole]
GO
GRANT UPDATE ON SCHEMA::[Product] TO [AppRole]
GO
GRANT VIEW CHANGE TRACKING ON SCHEMA::[Product] TO [AppRole]
GO
GRANT VIEW DEFINITION ON SCHEMA::[Product] TO [AppRole]
GO
DENY TAKE OWNERSHIP ON SCHEMA::[Product] TO [AppRole]
GO
