Use vizsga
GO

INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Rachet & Clank: Rift Apart','2021-06-11','Insomniac Games','Sony Interactive Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Dungeons & Dragons: Dark Alliance','2021-06-25','Tuque Games','Wizards of the Coast')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Scarlet Nexus','2021-06-29','BANDAI NAMCO Entertainment (America)','Bandai Namco Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Necromunda: Hired Gun','2021-06-04','Streum On Studio','Focus Home Interactive')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Backbone','2021-05-30','EggNut','Raw Fury/EggNut')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Sniper: Ghost Warrior Contracts 2','2021-06-07','CI Games','CI Games')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Legend of Mana','2021-06-24','Square Enix/M2 Co','Square Enix')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('The Last Spell','2021-05-31','CCCP','CCCP')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('The Elder Scrolls Online: Blackwood','2021-06-08','Zenimax Online Studios','Bethesda Softworks')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('The Medium','2021-01-28','Bloober Team','Bloober Team')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Resident Evil: Village','2021-05-15','Capcom','Capcom')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Outriders','2021-04-01','People Can Fly','Square Enix')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Biomutant','2021-05-25','Experiment 101','THQ Nordic')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Valheim','2021-02-02','Dvoid/Richard Svensson','Coffee Stain')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('It Takes Two','2021-03-26','Hazelight/Mohammad Almajali','Electronic Arts/Mohammad Almajali')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Mass Effect: Legendary Edition','2021-05-14','BioWare/Ea Swiss','Electronic Arts')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Subnautica: Below Zero','2021-05-14','Unknown Worlds Entertainment','Unknown Worlds Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Far Cry 6','2021-10-07','Ubisoft/Ubisoft Toronto','Ubisoft Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Returnal','2021-05-30','Housemarque','Sony Interactive Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Werewolf: The Apocalypse - Earthblood','2021-02-04','Cyanide Studio','Bigben Interactive')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Battlefield 2042','2021-10-22','Electronic Arts DICE/Citerion Games','Electronic Arts')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('The Dark Pictures Anthology: House of Ashes','2021-10-22','Supermassive Games','Bandai Namco Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Cyberpunk 2077','2020-12-10','CD PROJEKT RED/CD PROJEKT','CD PROJEKT RED')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('The Last of Us Part II','2020-06-19','Naughty Dog','Sony Interactive Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Ghost of Tsushima','2020-07-17','Sucker Punch Productions','Sony Interactive Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('DOOM Eternal','2020-03-20','Bethesda Softworks/id Software','Bethesda Softworks')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Doom Eternal: The Ancient Gods - Part One','2020-10-20','id Software','Bethesda Softworks')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Doom Eternal: The Ancient Gods - Part Two','2021-03-18','id Software','Bethesda Softworks')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Ori and the Will of the Wisps','2020-03-10','Moon Studios','Microsoft Studios/Xbox Game Studios')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Immortals: Fenyx Rising','2020-12-03','Ubisoft/Ubisoft Quebec','Ubisoft Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Crusade Kings III','2020-09-01','Paradox Development Studios','Paradox Interactive')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Call of Duty: Black Ops Cold War','2020-11-13','Raven Software/Treyarch','Activision')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Crash Bandicoot 4: Its About Time','2020-10-01','Toys for Bob','Activision Blizzard')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Wolcen: Lords of Mayhem','2020-02-13','WOLCEN Studio','WOLCEN Studio')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Mortal Shell','2020-08-18','PlayStack/Cold Symmetry','PlayStack')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Grounded','2020-07-28','Obsidian Entertainment','Xbox Game Studios')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Total War Saga: TROY','2020-08-13','Creative Assembly','SEGA')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Crysis Remastered','2020-09-18','Saber Interactive','Crytek')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('The Witcher 3: Wild Hunt','2015-05-18','CD PROJEKT RED','CD PROJEKT RED')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Red Dead Redemption 2','2018-10-26','Rockstar Games','Rockstar Games')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('S.T.A.L.K.E.R. 2: Heart of Chernobyl','2022-04-28','GSC Game World','GSC Game World')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Mass Effect 2','2010-01-26','BioWare','Electronic Arts')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Star Wars: Knights of the Old Republic','2003-07-15','Aspyr Media/BioWare/Lucasfilm','Aspyr/ LucasArts Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Star Wars: Knights of the Old Republic II - The Sith Lords','2004-12-06','Aspyr Media/Obsidian Entertainment/Lucasfilm','Aspyr/Disney Interactive/LucasArts Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('BioShock Infinite','2013-05-26','Aspyr Media/2K Australia/Irrational Games','2K Games/Aspyr')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Death Stranding','2019-11-08','Kojima Productions','505 Games/Sony Interactive Entertainment')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Age of Empires II: Age of Kings','1999-09-30','Ensemble Studios','Microsoft Studios')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('The Elder Scrolls V: Skyrim','2011-11-11','Bethesda Softworks/Bethesda Game Studios','Bethesda Softworks')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('INSIDE','2016-06-28','Playdead','Playdead')
INSERT INTO Product.Game([Game_name],[ReleaseDate],[Developer],[Publisher]) VALUES ('Dark Souls III','2016-05-11','BANDAI NAMCO Entertainment America/FromSoftware','Bandai Namco Entertainment/BANDAI NAMCO Entertainment US/FromSoftware')